spring:
  config:
    import:
      - optional:file:/etc/secret/application-secret.yaml
otel:
  propagators:
    - tracecontext
    - b3
    - baggage
management:
  otlp:
    tracing:
      endpoint: http://${NODE_IP:localhost}:4317
      transport: grpc
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    enabled: true
