server:
  port: 8080

jwt:
  access_secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
